from pystdf4.Core import C_n

from .base import StdfRecordBase


class DTR(StdfRecordBase):
    """
    Datalog Text Record (DTR)

    Function: Contains text information that is to be included in the datalog printout. DTRs may be written under the control of a job plan:
    for example, to highlight unexpected test results. They may also be generated by the tester executive software: for example, to indicate
    that the datalog sampling rate has changed. DTRs are placed as comments in the datalog listing.
    """

    REC_TYP = 50
    REC_SUB = 30

    TEXT_DAT: C_n
    """
    ASCII text string
    """

    def __init__(self, TEXT_DAT: str):
        self.TEXT_DAT = C_n(TEXT_DAT)
