from dataclasses import dataclass

from .DataType import U_2, C_n
from .DataType import UInt16, CharVarLen
from pystdf4.Records.StdfRecordBase import StdfRecordBase, register_record


@dataclass
@register_record(50, 10)
class GDR(StdfRecordBase):
    """
    Generic Data Record (GDR)

    Function: Contains information that does not conform to any other record type defined by the STDF specification. Such records are intended to be written under the control of job plans executing on the tester. This data may be used for any purpose that the user desires.
    """

    REC_TYP = 50
    REC_SUB = 10

    # TODO: Implement GEN_DATA

    FLD_CNT: UInt16 = U_2()
    """
    Count of data fields in record
    """

    # GEN_DATA: V_n =V_n()
    """
    Data type code and data for one field
    """


@dataclass
@register_record(50, 30)
class DTR(StdfRecordBase):
    """
    Datalog Text Record (DTR)

    Function: Contains text information that is to be included in the datalog printout. DTRs may be written under the control of a job plan: for example, to highlight unexpected test results. They may also be generated by the tester executive software: for example, to indicate that the datalog sampling rate has changed. DTRs are placed as comments in the datalog listing.
    """

    REC_TYP = 50
    REC_SUB = 30

    TEXT_DAT: CharVarLen = C_n()
    """
    ASCII text string
    """
